name: Deploy

on:
  push:
    branches: [ main ]  # Only trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      # Deploy to VPS using SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/chat-app
            git pull origin main
            docker-compose pull
            docker-compose up -d --build